#!/usr/bin/env bash
# Configure HAproxy

apt-get -y update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
cat >> /etc/haproxy/haproxy.cfg << EOF
frontend front
	bind *:80
	mode http
	default_backend back
backend back
    balance roundrobin
    server 2066-web-01 34.75.144.80:80 check
    server 2066-web-02 34.75.114.192:80 check
EOF
service haproxy restart
